In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv('India_Menu.csv')

In [4]:
df

,Menu Category,Menu Items,Per Serve Size,Energy (kCal),Protein (g),Total fat (g),Sat Fat (g),Trans fat (g),Cholesterols (mg),Total carbohydrate (g),Total Sugars (g),Added Sugars (g),Sodium (mg)
0,Regular Menu,McVeggie™ Burger,168 g,402.05,10.24,13.83,5.34,0.16,2.49,56.54,7.90,4.49,706.13
1,Regular Menu,McAloo Tikki Burger®,146 g,339.52,8.50,11.31,4.27,0.20,1.47,50.27,7.05,4.07,545.34
2,Regular Menu,McSpicy™ Paneer Burger,199 g,652.76,20.29,39.45,17.12,0.18,21.85,52.33,8.35,5.27,1074.58
3,Regular Menu,Spicy Paneer Wrap,250 g,674.68,20.96,39.10,19.73,0.26,40.93,59.27,3.50,1.08,1087.46
4,Regular Menu,American Veg Burger,177 g,512.17,15.30,23.45,10.51,0.17,25.24,56.96,7.85,4.76,1051.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Condiments Menu,Tomato Ketchup Sachets,8 g,11.23,0.08,23.45,0.00,0.01,0.08,2.63,2.33,1.64,71.05
137,Condiments Menu,Maple Syrup,30 g,86.40,0.00,0.00,0.00,0.00,0.30,21.60,16.20,5.34,15.00
138,Condiments Menu,Cheese Slice,14 g,51.03,3.06,3.99,2.89,0.01,13.43,0.72,0.54,0.00,178.95
139,Condiments Menu,Sweet Corn,40 g,45.08,1.47,1.00,0.22,0.04,2.00,7.55,2.54,0.00,0.04
140,Condiments Menu,Mixed Fruit Beverage,180 ml,72.25,0.65,0.02,0.02,0.02,0.01,18.00,16.83,0.00,10.80

In [5]:
df['Menu Category'].value_counts()

McCafe Menu        51
Regular Menu       36
Beverages Menu     17
Breakfast Menu     15
Gourmet Menu       11
Condiments Menu     9
Desserts Menu       2
Name: Menu Category, dtype: int64

In [6]:
grp = df.groupby('Menu Category')['Menu Items']

In [7]:
grp.describe()

                count unique                             top freq
Menu Category
Beverages Menu     17     17                 Small Coca-Cola    1
Breakfast Menu     15     15                    Veg McMuffin    1
Condiments Menu     9      9            Mustard diping sauce    1
Desserts Menu       2      2           Small McFlurry - Oreo    1
Gourmet Menu       11     11  American Triple Cheese Chicken    1
McCafe Menu        51     51                  Cappuccino (L)    1
Regular Menu       36     36                McVeggie™ Burger    1

In [17]:
df['Per Serve Size']

0        168
1        146
2        199
3        250
4        177
        ...
136        8
137       30
138       14
139       40
140    180 ml
Name: Per Serve Size, Length: 141, dtype: object

In [16]:
df['Per Serve Size'] = df['Per Serve Size'].str.replace('g', '')

In [18]:
df['Per Serve Size'] = df['Per Serve Size'].str.replace('ml', '')

In [22]:
df['Per Serve Size'].astype(float)

0      168.0
1      146.0
2      199.0
3      250.0
4      177.0
       ...
136      8.0
137     30.0
138     14.0
139     40.0
140    180.0
Name: Per Serve Size, Length: 141, dtype: float64

0      168
1      146
2      199
3      250
4      177
       ...
136      8
137     30
138     14
139     40
140    180
Name: Per Serve Size, Length: 141, dtype: object